# -*- coding: utf-8 -*-
"""Egyptian_Artifact_VLM

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iI0w7zoCivAT3c_TlbCTZTfWRPwpHrya
"""

from google.colab import drive
drive.mount('/content/drive')

# Commented out IPython magic to ensure Python compatibility.
import os
os.makedirs('/content/drive/MyDrive/Egyptian_Artifact_VLM', exist_ok=True)
# %cd /content/drive/MyDrive/Egyptian_Artifact_VLM
print("Working directory:", os.getcwd())

folders = [
    'data/raw', 'data/images', 'data/processed',
    'datalists', 'notebooks', 'src',
    'configs', 'checkpoints', 'figures', 'docs'
]
for f in folders:
    os.makedirs(f, exist_ok=True)

print("Folder structure created:")
for f in folders:
    print(f"  ✓ {f}")

!pip install -q transformers peft datasets accelerate \
               trl wandb gradio rouge-score Pillow pandas
print("✓ All dependencies installed!")

import os
os.environ['KAGGLE_USERNAME'] = 'meghanam27'
os.environ['KAGGLE_KEY'] = 'KGAT_a770a9fdeec680a67cd4bbd870902cab'

!kaggle datasets list --search "british museum egyptian"

!kaggle datasets download -d dkaane/british-museum-egyptian-objects-700-330-bce --path data/raw/
print("✓ Download complete!")

!unzip -q data/raw/british-museum-egyptian-objects-700-330-bce.zip -d data/raw/
print("✓ Unzipped!")

import os
files = os.listdir('data/raw/')
print("Files found:")
for f in files:
    print(f"  {f}")

import pandas as pd

df = pd.read_csv('data/raw/EgyptBritishMuseum-2021-03-05CSVUnique.csv')
print("Shape:", df.shape)
print("\nColumns:")
for col in df.columns.tolist():
    print(f"  {col}")
print("\nFirst row:")
print(df.iloc[0].to_dict())

import pandas as pd

df = pd.read_csv('data/raw/EgyptBritishMuseum-2021-03-05CSVUnique.csv')

# check how many have images
has_image = df['Image'].notna()
print(f"Total records: {len(df)}")
print(f"Records with images: {has_image.sum()}")
print(f"Records without images: {(~has_image).sum()}")

# check key columns for nulls
key_cols = ['Image', 'Object type', 'Description', 'Materials', 'Culture', 'Production date']
print("\nNon-null counts for key columns:")
for col in key_cols:
    print(f"  {col}: {df[col].notna().sum()}")

# top object types
print("\nTop 15 object types:")
print(df['Object type'].value_counts().head(15))

# filter to records with images only
df_img = df[df['Image'].notna()].copy()

# filter to Egyptian culture
egyptian = df_img[df_img['Culture'].str.contains('Egypt|Late Period|Ptolem|Nubian|Saite',
                                                    case=False, na=False)]
print(f"Egyptian records with images: {len(egyptian)}")

# top object types in Egyptian subset
print("\nTop 20 Egyptian object types:")
print(egyptian['Object type'].value_counts().head(20))

# check culture values
print("\nCulture values:")
print(egyptian['Culture'].value_counts().head(15))

# filter to most meaningful object types for reasoning
target_types = ['figure', 'amulet', 'scarab', 'coffin-fitting',
                'vessel', 'amulet; figure', 'figure; plaque',
                'votive box; figure', 'scarab-mould']

clean = egyptian[egyptian['Object type'].isin(target_types)].copy()
clean = clean[['Image', 'Object type', 'Description', 'Materials',
               'Culture', 'Production date', 'Find spot',
               'Curators Comments', 'objid']].reset_index(drop=True)

print(f"Clean subset: {len(clean)} records")
print(clean['Object type'].value_counts())

clean.to_csv('datalists/egyptian_artifacts_clean.csv', index=False)
print("✓ Saved to datalists/egyptian_artifacts_clean.csv")

import requests
import os
from pathlib import Path
import time
from tqdm import tqdm

# create image directory
os.makedirs('data/images', exist_ok=True)

success = 0
failed = 0
failed_ids = []

for idx, row in tqdm(clean.iterrows(), total=len(clean)):
    url = row['Image']
    obj_id = str(row['objid'])[:8]  # short id for filename
    obj_type = str(row['Object type']).replace('/', '_').replace(' ', '_')
    filename = f"data/images/{obj_type}_{obj_id}.jpg"

    # skip if already downloaded
    if os.path.exists(filename):
        success += 1
        continue

    try:
        response = requests.get(url, timeout=10)
        if response.status_code == 200:
            with open(filename, 'wb') as f:
                f.write(response.content)
            success += 1
        else:
            failed += 1
            failed_ids.append(obj_id)
    except Exception as e:
        failed += 1
        failed_ids.append(obj_id)

    time.sleep(0.2)  # be polite to the server

print(f"\n✓ Downloaded: {success}")
print(f"✗ Failed: {failed}")
print(f"Total images in folder: {len(os.listdir('data/images'))}")

import requests

# test a single URL
test_url = clean['Image'].iloc[0]
print("Testing URL:", test_url)

response = requests.get(test_url, timeout=10, verify=False)
print("Status code:", response.status_code)
print("Response:", response.text[:200])

import requests
import os
import time
from tqdm import tqdm

os.makedirs('data/images', exist_ok=True)

success = 0
failed = 0

for idx, row in tqdm(clean.iterrows(), total=len(clean)):
    url = row['Image']
    obj_id = str(row['objid'])[:8]
    obj_type = str(row['Object type']).replace('/', '_').replace(' ', '_')
    filename = f"data/images/{obj_type}_{obj_id}.jpg"

    if os.path.exists(filename):
        success += 1
        continue

    try:
        response = requests.get(url, timeout=10, verify=False)  # ← fix
        if response.status_code == 200:
            with open(filename, 'wb') as f:
                f.write(response.content)
            success += 1
        else:
            failed += 1
    except Exception as e:
        failed += 1

    time.sleep(0.2)

print(f"\n✓ Downloaded: {success}")
print(f"✗ Failed: {failed}")
print(f"Total images in folder: {len(os.listdir('data/images'))}")

import matplotlib.pyplot as plt
import matplotlib.image as mpimg
import os
import random

image_files = os.listdir('data/images/')
sample = random.sample(image_files, 6)

fig, axes = plt.subplots(2, 3, figsize=(12, 8))
for ax, fname in zip(axes.flatten(), sample):
    img = mpimg.imread(f'data/images/{fname}')
    ax.imshow(img)
    ax.set_title(fname[:30], fontsize=8)
    ax.axis('off')

plt.tight_layout()
plt.savefig('figures/sample_artifacts.png')
plt.show()
print("✓ Sample images displayed!")

import pandas as pd
import matplotlib.pyplot as plt
from PIL import Image
import os

# basic stats
image_files = os.listdir('data/images/')
print(f"Total images: {len(image_files)}")

# check image sizes
sizes = []
for fname in image_files:
    try:
        img = Image.open(f'data/images/{fname}')
        sizes.append(img.size)
    except:
        pass

widths = [s[0] for s in sizes]
heights = [s[1] for s in sizes]
print(f"Average width:  {sum(widths)//len(widths)}px")
print(f"Average height: {sum(heights)//len(heights)}px")
print(f"Min size: {min(widths)}x{min(heights)}")
print(f"Max size: {max(widths)}x{max(heights)}")

# object type distribution
fig, ax = plt.subplots(figsize=(10, 5))
clean['Object type'].value_counts().plot(kind='bar', ax=ax, color='steelblue')
ax.set_title('Object type distribution')
ax.set_xlabel('Object type')
ax.set_ylabel('Count')
plt.tight_layout()
plt.savefig('figures/object_type_distribution.png')
plt.show()
print("✓ EDA complete!")

import os

# add filename column to clean dataframe
image_files = os.listdir('data/images/')

# match images back to metadata
clean['filename'] = clean.apply(
    lambda row: f"{str(row['Object type']).replace('/', '_').replace(' ', '_')}_{str(row['objid'])[:8]}.jpg",
    axis=1
)

# verify matches
clean['file_exists'] = clean['filename'].apply(
    lambda f: os.path.exists(f'data/images/{f}')
)

print(f"Matched: {clean['file_exists'].sum()}")
print(f"Unmatched: {(~clean['file_exists']).sum()}")

# save final manifest
clean.to_csv('datalists/dataset_manifest.csv', index=False)
print("✓ Dataset manifest saved!")
print(f"\nFinal dataset: {clean['file_exists'].sum()} images with metadata")
print(f"Object types: {clean['Object type'].nunique()}")
print(f"Materials: {clean['Materials'].nunique()}")
print(f"Cultures: {clean['Culture'].nunique()}")

!pip install -q git+https://github.com/openai/CLIP.git
import clip
import torch

# check GPU is available
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"✓ CLIP installed!")
print(f"✓ Device: {device}")

# load CLIP model
model, preprocess = clip.load("ViT-L/14", device=device)
print(f"✓ CLIP ViT-L/14 loaded!")
print(f"  Vision encoder output dim: {model.visual.output_dim}")

import torch
import clip
from PIL import Image
import os

# test with a single image first
sample_file = os.listdir('data/images/')[0]
image = preprocess(Image.open(f'data/images/{sample_file}')).unsqueeze(0).to(device)

# define text labels for zero-shot classification
object_type_labels = [
    "a shabti figurine",
    "an amulet",
    "a scarab",
    "a coffin fitting",
    "a vessel",
    "a votive figure",
    "a plaque",
    "a votive box",
    "a scarab mould"
]

# encode text labels
text_tokens = clip.tokenize(object_type_labels).to(device)

# get predictions
with torch.no_grad():
    image_features = model.encode_image(image)
    text_features = model.encode_text(text_tokens)

    # normalize
    image_features /= image_features.norm(dim=-1, keepdim=True)
    text_features /= text_features.norm(dim=-1, keepdim=True)

    # compute similarity scores
    similarity = (100.0 * image_features @ text_features.T).softmax(dim=-1)

# show results
print(f"Image: {sample_file}")
print(f"\nCLIP zero-shot predictions:")
scores, indices = similarity[0].topk(3)
for score, idx in zip(scores, indices):
    print(f"  {object_type_labels[idx]:30s} → {score.item():.1f}%")

# now add reasoning explanation
top_label = object_type_labels[indices[0]]
top_score = scores[0].item()

print(f"\n--- Reasoning Output ---")
print(f"Object detected: {top_label} ({top_score:.1f}% confidence)")
print(f"Because: CLIP found strong visual similarity between this artifact")
print(f"         image and the text description '{top_label}'")
print(f"         based on shape, texture, and iconographic features.")

# better prompts — more descriptive, domain-specific
detailed_labels = [
    "an ancient Egyptian shabti figurine with mummiform shape and hieroglyphic inscriptions",
    "a small ancient Egyptian amulet charm made of faience or bronze",
    "an ancient Egyptian scarab beetle amulet with carved underside",
    "an ancient Egyptian coffin fitting or funerary decoration",
    "an ancient Egyptian ceramic or stone vessel or jar",
    "an ancient Egyptian votive bronze or faience human figurine",
    "an ancient Egyptian carved stone or faience plaque with relief decoration",
    "an ancient Egyptian votive box or container with figure",
    "an ancient Egyptian scarab mould for casting amulets"
]

# run again with better prompts
text_tokens = clip.tokenize(detailed_labels).to(device)

with torch.no_grad():
    image_features = model.encode_image(image)
    text_features = model.encode_text(text_tokens)
    image_features /= image_features.norm(dim=-1, keepdim=True)
    text_features /= text_features.norm(dim=-1, keepdim=True)
    similarity = (100.0 * image_features @ text_features.T).softmax(dim=-1)

print(f"Image: {sample_file}")
print(f"Actual label: amulet\n")
print(f"CLIP predictions with detailed prompts:")
scores, indices = similarity[0].topk(3)
for score, idx in zip(scores, indices):
    print(f"  {score.item():.1f}%  →  {detailed_labels[idx][:60]}")

# check if correct
top_label = detailed_labels[indices[0]]
correct = "amulet" in top_label
print(f"\nCorrect: {'✓ YES' if correct else '✗ NO'}")
print(f"Top confidence: {scores[0].item():.1f}%")

import pandas as pd
from PIL import Image
import torch
import clip
import os
from tqdm import tqdm

# label mapping — short name to detailed prompt
label_map = {
    "figure":             "an ancient Egyptian votive bronze or faience human figurine",
    "amulet":             "a small ancient Egyptian amulet charm made of faience or bronze",
    "scarab":             "an ancient Egyptian scarab beetle amulet with carved underside",
    "coffin-fitting":     "an ancient Egyptian coffin fitting or funerary decoration",
    "vessel":             "an ancient Egyptian ceramic or stone vessel or jar",
    "amulet; figure":     "a small ancient Egyptian amulet charm made of faience or bronze",
    "figure; plaque":     "an ancient Egyptian carved stone or faience plaque with relief decoration",
    "votive box; figure": "an ancient Egyptian votive box or container with figure",
    "scarab-mould":       "an ancient Egyptian scarab mould for casting amulets"
}

detailed_labels = list(set(label_map.values()))
text_tokens = clip.tokenize(detailed_labels).to(device)

with torch.no_grad():
    text_features = model.encode_text(text_tokens)
    text_features /= text_features.norm(dim=-1, keepdim=True)

correct = 0
total = 0
results = []

for _, row in tqdm(clean.iterrows(), total=len(clean)):
    fname = row['filename']
    true_label = row['Object type']
    img_path = f"data/images/{fname}"

    if not os.path.exists(img_path):
        continue

    try:
        image = preprocess(Image.open(img_path)).unsqueeze(0).to(device)

        with torch.no_grad():
            image_features = model.encode_image(image)
            image_features /= image_features.norm(dim=-1, keepdim=True)
            similarity = (100.0 * image_features @ text_features.T).softmax(dim=-1)

        top_idx = similarity[0].argmax().item()
        predicted_prompt = detailed_labels[top_idx]
        confidence = similarity[0].max().item()

        # check if prediction matches true label
        expected_prompt = label_map.get(true_label, "")
        is_correct = predicted_prompt == expected_prompt

        if is_correct:
            correct += 1
        total += 1

        results.append({
            'filename': fname,
            'true_label': true_label,
            'predicted_prompt': predicted_prompt,
            'confidence': round(confidence, 4),
            'correct': is_correct
        })

    except Exception as e:
        continue

accuracy = correct / total * 100
print(f"\n✓ Baseline evaluation complete!")
print(f"Total images evaluated: {total}")
print(f"Correct predictions:    {correct}")
print(f"Zero-shot accuracy:     {accuracy:.1f}%")

# save results
results_df = pd.DataFrame(results)
results_df.to_csv('datalists/baseline_results.csv', index=False)
print(f"✓ Results saved to datalists/baseline_results.csv")

import pandas as pd

results_df = pd.read_csv('datalists/baseline_results.csv')

# accuracy per object type
print("Accuracy by object type:")
print("-" * 45)
for obj_type in clean['Object type'].unique():
    subset = results_df[results_df['true_label'] == obj_type]
    acc = subset['correct'].mean() * 100
    count = len(subset)
    bar = '█' * int(acc / 5)
    print(f"{obj_type:25s} {acc:5.1f}%  ({count} images)  {bar}")

# most common mistakes
print("\nTop 10 mistakes:")
print("-" * 45)
wrong = results_df[results_df['correct'] == False]
print(wrong.groupby(['true_label', 'predicted_prompt']).size()
        .sort_values(ascending=False)
        .head(10)
        .to_string())

# average confidence correct vs wrong
print(f"\nAvg confidence when correct: {results_df[results_df['correct']]['confidence'].mean():.4f}")
print(f"Avg confidence when wrong:   {results_df[~results_df['correct']]['confidence'].mean():.4f}")

def generate_reasoning(image_path, true_label, row):
    """
    Given an image and its metadata, generate a chain-of-thought
    reasoning explanation grounded in visible features.
    """
    image = preprocess(Image.open(image_path)).unsqueeze(0).to(device)

    # visual feature probes — what CLIP can detect
    visual_probes = {
        "shape": [
            "a mummiform or wrapped shape",
            "a beetle or oval shape",
            "a human or animal figurine shape",
            "a flat rectangular plaque shape",
            "a cylindrical or vessel shape",
            "a box or container shape"
        ],
        "material": [
            "made of blue or green faience glaze",
            "made of dark bronze or copper metal",
            "made of white or grey limestone",
            "made of gold or gilded material",
            "made of red or brown terracotta clay",
            "made of black basalt stone"
        ],
        "surface": [
            "with hieroglyphic inscriptions or text",
            "with carved relief decoration",
            "with painted decoration",
            "with smooth undecorated surface",
            "with animal or deity iconography"
        ]
    }

    observations = {}

    for feature, probes in visual_probes.items():
        tokens = clip.tokenize(probes).to(device)
        with torch.no_grad():
            image_features = model.encode_image(image)
            text_features = model.encode_text(tokens)
            image_features /= image_features.norm(dim=-1, keepdim=True)
            text_features  /= text_features.norm(dim=-1, keepdim=True)
            sim = (100.0 * image_features @ text_features.T).softmax(dim=-1)
        top_idx = sim[0].argmax().item()
        top_score = sim[0].max().item()
        observations[feature] = (probes[top_idx], round(top_score, 3))

    # build reasoning explanation
    material  = row['Materials'] if pd.notna(row['Materials']) else observations['material'][0]
    period    = row['Culture']   if pd.notna(row['Culture'])   else 'Late Period'
    date      = row['Production date'] if pd.notna(row['Production date']) else 'unknown date'

    reasoning = f"""[Observation]
- Shape:    {observations['shape'][0]}
- Material: {observations['material'][0]}
- Surface:  {observations['surface'][0]}

[Reasoning]
The detected shape ({observations['shape'][0]}) combined with
{observations['material'][0]} is characteristic of a {true_label}
from the {period} ({date}).
The surface detail ({observations['surface'][0]}) further supports
this classification based on typical Late Period Egyptian craftsmanship.

[Conclusion]
Artifact type: {true_label}
Material:      {material}
Period:        {period}
Date:          {date}"""

    return reasoning, observations


# test on 3 sample images
print("=" * 60)
for i, (_, row) in enumerate(clean.sample(3, random_state=42).iterrows()):
    img_path = f"data/images/{row['filename']}"
    reasoning, obs = generate_reasoning(img_path, row['Object type'], row)
    print(f"\nImage: {row['filename']}")
    print(reasoning)
    print("=" * 60)

import json
from tqdm import tqdm

reasoning_outputs = []

for _, row in tqdm(clean.iterrows(), total=len(clean)):
    img_path = f"data/images/{row['filename']}"
    if not os.path.exists(img_path):
        continue
    try:
        reasoning, observations = generate_reasoning(
            img_path, row['Object type'], row
        )
        reasoning_outputs.append({
            'filename':    row['filename'],
            'object_type': row['Object type'],
            'material':    row['Materials'],
            'period':      row['Culture'],
            'date':        row['Production date'],
            'shape_obs':   observations['shape'][0],
            'material_obs':observations['material'][0],
            'surface_obs': observations['surface'][0],
            'reasoning':   reasoning
        })
    except Exception as e:
        continue

# save as JSON
with open('datalists/reasoning_outputs.json', 'w') as f:
    json.dump(reasoning_outputs, f, indent=2)

# save as JSONL for SFT training (NV-Reason-CXR format)
with open('datalists/sft.jsonl', 'w') as f:
    for item in reasoning_outputs:
        record = {
            "image": f"images/{item['filename']}",
            "conversations": [
                {
                    "role": "user",
                    "content": "You are an expert Egyptologist. Examine this artifact and explain your reasoning about what it is, citing visible features."
                },
                {
                    "role": "assistant",
                    "content": item['reasoning']
                }
            ]
        }
        f.write(json.dumps(record) + '\n')

print(f"✓ Reasoning outputs saved: {len(reasoning_outputs)} records")
print(f"✓ SFT training file saved: datalists/sft.jsonl")
print(f"\nSample SFT record:")
print(json.dumps(reasoning_outputs[0], indent=2)[:500])

from transformers import GPT2Tokenizer, GPT2LMHeadModel
import torch

# load distilgpt2 as language decoder
tokenizer = GPT2Tokenizer.from_pretrained('distilgpt2')
tokenizer.pad_token = tokenizer.eos_token

decoder = GPT2LMHeadModel.from_pretrained('distilgpt2').to(device)

print(f"✓ Language decoder loaded!")
print(f"  Model: distilgpt2")
print(f"  Parameters: {sum(p.numel() for p in decoder.parameters()):,}")
print(f"  Device: {device}")

import torch
from torch.utils.data import Dataset, DataLoader
import json

class ArtifactReasoningDataset(Dataset):
    def __init__(self, jsonl_path, tokenizer, max_length=256):
        self.samples = []
        self.tokenizer = tokenizer
        self.max_length = max_length

        with open(jsonl_path, 'r') as f:
            for line in f:
                record = json.loads(line)
                # combine user prompt + assistant reasoning as training text
                text = (
                    "Examine this Egyptian artifact and explain your reasoning.\n\n"
                    + record['conversations'][1]['content']
                    + tokenizer.eos_token
                )
                self.samples.append(text)

    def __len__(self):
        return len(self.samples)

    def __getitem__(self, idx):
        tokens = self.tokenizer(
            self.samples[idx],
            max_length=self.max_length,
            padding='max_length',
            truncation=True,
            return_tensors='pt'
        )
        input_ids = tokens['input_ids'].squeeze()
        attention_mask = tokens['attention_mask'].squeeze()
        return {
            'input_ids': input_ids,
            'attention_mask': attention_mask,
            'labels': input_ids.clone()
        }

# create dataset and dataloader
dataset = ArtifactReasoningDataset('datalists/sft.jsonl', tokenizer)
dataloader = DataLoader(dataset, batch_size=8, shuffle=True)

print(f"✓ Dataset created!")
print(f"  Total samples: {len(dataset)}")
print(f"  Batches per epoch: {len(dataloader)}")
print(f"  Sample text preview:")
print(dataset.samples[0][:300])

from transformers import get_linear_schedule_with_warmup
from torch.optim import AdamW
import os

# training config
EPOCHS = 3
LR = 5e-5
SAVE_PATH = 'checkpoints/decoder_sft.pt'
os.makedirs('checkpoints', exist_ok=True)

# optimizer and scheduler
optimizer = AdamW(decoder.parameters(), lr=LR)
scheduler = get_linear_schedule_with_warmup(
    optimizer,
    num_warmup_steps=10,
    num_training_steps=len(dataloader) * EPOCHS
)

# training loop
decoder.train()
for epoch in range(EPOCHS):
    total_loss = 0
    for batch_idx, batch in enumerate(dataloader):
        input_ids      = batch['input_ids'].to(device)
        attention_mask = batch['attention_mask'].to(device)
        labels         = batch['labels'].to(device)

        optimizer.zero_grad()
        outputs = decoder(
            input_ids=input_ids,
            attention_mask=attention_mask,
            labels=labels
        )
        loss = outputs.loss
        loss.backward()
        torch.nn.utils.clip_grad_norm_(decoder.parameters(), 1.0)
        optimizer.step()
        scheduler.step()

        total_loss += loss.item()

        if batch_idx % 30 == 0:
            print(f"Epoch {epoch+1}/{EPOCHS} | "
                  f"Batch {batch_idx}/{len(dataloader)} | "
                  f"Loss: {loss.item():.4f}")

    avg_loss = total_loss / len(dataloader)
    print(f"\n✓ Epoch {epoch+1} complete — Avg Loss: {avg_loss:.4f}\n")

# save model
torch.save(decoder.state_dict(), SAVE_PATH)
print(f"✓ Model saved to {SAVE_PATH}")

decoder.eval()

def generate_full_reasoning(image_path, row):
    # step 1 — CLIP extracts visual observations
    image = preprocess(Image.open(image_path)).unsqueeze(0).to(device)

    visual_probes = {
        "shape": [
            "a mummiform or wrapped shape",
            "a beetle or oval shape",
            "a human or animal figurine shape",
            "a flat rectangular plaque shape",
            "a cylindrical or vessel shape",
            "a box or container shape"
        ],
        "material": [
            "made of blue or green faience glaze",
            "made of dark bronze or copper metal",
            "made of white or grey limestone",
            "made of gold or gilded material",
            "made of red or brown terracotta clay",
            "made of black basalt stone"
        ],
        "surface": [
            "with hieroglyphic inscriptions or text",
            "with carved relief decoration",
            "with painted decoration",
            "with smooth undecorated surface",
            "with animal or deity iconography"
        ]
    }

    observations = {}
    for feature, probes in visual_probes.items():
        tokens = clip.tokenize(probes).to(device)
        with torch.no_grad():
            img_feat  = model.encode_image(image)
            txt_feat  = model.encode_text(tokens)
            img_feat /= img_feat.norm(dim=-1, keepdim=True)
            txt_feat /= txt_feat.norm(dim=-1, keepdim=True)
            sim = (100.0 * img_feat @ txt_feat.T).softmax(dim=-1)
        top_idx = sim[0].argmax().item()
        observations[feature] = probes[top_idx]

    # step 2 — build prompt for decoder
    prompt = (
        f"Examine this Egyptian artifact and explain your reasoning.\n\n"
        f"[Observation]\n"
        f"- Shape:    {observations['shape']}\n"
        f"- Material: {observations['material']}\n"
        f"- Surface:  {observations['surface']}\n\n"
        f"[Reasoning]\n"
    )

    # step 3 — decoder generates reasoning + conclusion
    input_ids = tokenizer.encode(prompt, return_tensors='pt').to(device)
    with torch.no_grad():
        output_ids = decoder.generate(
            input_ids,
            max_new_tokens=150,
            temperature=0.7,
            do_sample=True,
            pad_token_id=tokenizer.eos_token_id
        )
    generated = tokenizer.decode(output_ids[0], skip_special_tokens=True)
    return generated, observations

# test on 3 unseen images
print("=" * 60)
for _, row in clean.sample(3, random_state=99).iterrows():
    img_path = f"data/images/{row['filename']}"
    output, obs = generate_full_reasoning(img_path, row)
    print(f"\nImage:       {row['filename']}")
    print(f"True label:  {row['Object type']} | {row['Materials']} | {row['Culture']}")
    print(f"\nGenerated reasoning:")
    print(output)
    print("=" * 60)

# fix attention mask warning
def generate_full_reasoning_v2(image_path, row):
    image = preprocess(Image.open(image_path)).unsqueeze(0).to(device)

    visual_probes = {
        "shape": [
            "a mummiform or wrapped shape",
            "a beetle or oval shape",
            "a human or animal figurine shape",
            "a flat rectangular plaque shape",
            "a cylindrical or vessel shape",
            "a box or container shape"
        ],
        "material": [
            "made of blue or green faience glaze",
            "made of dark bronze or copper metal",
            "made of white or grey limestone",
            "made of gold or gilded material",
            "made of red or brown terracotta clay",
            "made of black basalt stone"
        ],
        "surface": [
            "with hieroglyphic inscriptions or text",
            "with carved relief decoration",
            "with painted decoration",
            "with smooth undecorated surface",
            "with animal or deity iconography"
        ]
    }

    observations = {}
    for feature, probes in visual_probes.items():
        tokens = clip.tokenize(probes).to(device)
        with torch.no_grad():
            img_feat  = model.encode_image(image)
            txt_feat  = model.encode_text(tokens)
            img_feat /= img_feat.norm(dim=-1, keepdim=True)
            txt_feat /= txt_feat.norm(dim=-1, keepdim=True)
            sim = (100.0 * img_feat @ txt_feat.T).softmax(dim=-1)
        top_idx = sim[0].argmax().item()
        observations[feature] = probes[top_idx]

    prompt = (
        f"Examine this Egyptian artifact and explain your reasoning.\n\n"
        f"[Observation]\n"
        f"- Shape:    {observations['shape']}\n"
        f"- Material: {observations['material']}\n"
        f"- Surface:  {observations['surface']}\n\n"
        f"[Reasoning]\n"
    )

    # fix — explicit attention mask
    encoded = tokenizer(prompt, return_tensors='pt').to(device)
    with torch.no_grad():
        output_ids = decoder.generate(
            encoded['input_ids'],
            attention_mask=encoded['attention_mask'],
            max_new_tokens=150,
            temperature=0.7,
            do_sample=True,
            pad_token_id=tokenizer.eos_token_id
        )
    generated = tokenizer.decode(output_ids[0], skip_special_tokens=True)
    return generated, observations

# final evaluation — accuracy + ROUGE-L score
from rouge_score import rouge_scorer
scorer = rouge_scorer.RougeScorer(['rougeL'], use_stemmer=True)

correct = 0
total = 0
rouge_scores = []

for _, row in tqdm(clean.iterrows(), total=len(clean)):
    img_path = f"data/images/{row['filename']}"
    if not os.path.exists(img_path):
        continue
    try:
        generated, _ = generate_full_reasoning_v2(img_path, row)

        # classification accuracy
        if row['Object type'].lower() in generated.lower():
            correct += 1
        total += 1

        # rouge-l score
        reference = f"Artifact type: {row['Object type']}\nMaterial: {row['Materials']}\nPeriod: {row['Culture']}"
        score = scorer.score(reference, generated)
        rouge_scores.append(score['rougeL'].fmeasure)

    except Exception:
        continue

accuracy = correct / total * 100
avg_rouge = sum(rouge_scores) / len(rouge_scores)

print(f"\n{'='*45}")
print(f"  FINAL EVALUATION RESULTS")
print(f"{'='*45}")
print(f"  Total images:        {total}")
print(f"  Classification acc:  {accuracy:.1f}%")
print(f"  ROUGE-L score:       {avg_rouge:.4f}")
print(f"{'='*45}")
print(f"\n  Baseline (CLIP zero-shot): 41.9%")
print(f"  Our model:                 {accuracy:.1f}%")
improvement = accuracy - 41.9
print(f"  Improvement:               +{improvement:.1f}%")

!pip install -q gradio
import gradio as gr
from PIL import Image
import torch

def analyze_artifact(image):
    try:
        # preprocess image
        img_tensor = preprocess(image).unsqueeze(0).to(device)

        # visual probes
        visual_probes = {
            "shape": [
                "a mummiform or wrapped shape",
                "a beetle or oval shape",
                "a human or animal figurine shape",
                "a flat rectangular plaque shape",
                "a cylindrical or vessel shape",
                "a box or container shape"
            ],
            "material": [
                "made of blue or green faience glaze",
                "made of dark bronze or copper metal",
                "made of white or grey limestone",
                "made of gold or gilded material",
                "made of red or brown terracotta clay",
                "made of black basalt stone"
            ],
            "surface": [
                "with hieroglyphic inscriptions or text",
                "with carved relief decoration",
                "with painted decoration",
                "with smooth undecorated surface",
                "with animal or deity iconography"
            ]
        }

        observations = {}
        for feature, probes in visual_probes.items():
            tokens = clip.tokenize(probes).to(device)
            with torch.no_grad():
                img_feat  = model.encode_image(img_tensor)
                txt_feat  = model.encode_text(tokens)
                img_feat /= img_feat.norm(dim=-1, keepdim=True)
                txt_feat /= txt_feat.norm(dim=-1, keepdim=True)
                sim = (100.0 * img_feat @ txt_feat.T).softmax(dim=-1)
            top_idx = sim[0].argmax().item()
            observations[feature] = probes[top_idx]

        # build prompt
        prompt = (
            f"Examine this Egyptian artifact and explain your reasoning.\n\n"
            f"[Observation]\n"
            f"- Shape:    {observations['shape']}\n"
            f"- Material: {observations['material']}\n"
            f"- Surface:  {observations['surface']}\n\n"
            f"[Reasoning]\n"
        )

        # generate reasoning
        encoded = tokenizer(prompt, return_tensors='pt').to(device)
        with torch.no_grad():
            output_ids = decoder.generate(
                encoded['input_ids'],
                attention_mask=encoded['attention_mask'],
                max_new_tokens=150,
                temperature=0.7,
                do_sample=True,
                pad_token_id=tokenizer.eos_token_id
            )
        return tokenizer.decode(output_ids[0], skip_special_tokens=True)

    except Exception as e:
        return f"Error: {str(e)}"

# launch demo
demo = gr.Interface(
    fn=analyze_artifact,
    inputs=gr.Image(type="pil", label="Upload Egyptian Artifact Image"),
    outputs=gr.Textbox(label="Model Reasoning", lines=15),
    title="Egyptian_Artifact_VLM",
    description="Upload an image of a Late Period Egyptian artifact (700–330 BCE). The model will reason about what it is, citing visible visual features.",
    examples=[
        [f"data/images/{os.listdir('data/images/')[0]}"],
        [f"data/images/{os.listdir('data/images/')[100]}"],
        [f"data/images/{os.listdir('data/images/')[150]}"],
        [f"data/images/{os.listdir('data/images/')[200]}"],
        [f"data/images/{os.listdir('data/images/')[250]}"],
        [f"data/images/{os.listdir('data/images/')[300]}"],
        [f"data/images/{os.listdir('data/images/')[350]}"],
        [f"data/images/{os.listdir('data/images/')[400]}"]
    ]
)

demo.launch(share=True)

import os
os.makedirs('/content/drive/MyDrive/Egyptian_Artifact_VLM/hf_space', exist_ok=True)

# save tokenizer and decoder
tokenizer.save_pretrained('/content/drive/MyDrive/Egyptian_Artifact_VLM/hf_space/tokenizer')
decoder.save_pretrained('/content/drive/MyDrive/Egyptian_Artifact_VLM/hf_space/decoder')

print("✓ Model files saved!")
print(os.listdir('/content/drive/MyDrive/Egyptian_Artifact_VLM/hf_space/'))

reqs = """gradio
torch
transformers
Pillow
ftfy
regex
git+https://github.com/openai/CLIP.git
"""

with open('/content/drive/MyDrive/Egyptian_Artifact_VLM/hf_space/requirements.txt', 'w') as f:
    f.write(reqs)

print("✓ requirements.txt created!")

app_code = '''import gradio as gr
import torch
import clip
from transformers import GPT2Tokenizer, GPT2LMHeadModel
from PIL import Image

device = "cuda" if torch.cuda.is_available() else "cpu"

model, preprocess = clip.load("ViT-L/14", device=device)

tokenizer = GPT2Tokenizer.from_pretrained("./tokenizer")
tokenizer.pad_token = tokenizer.eos_token
decoder = GPT2LMHeadModel.from_pretrained("./decoder").to(device)
decoder.eval()

def analyze_artifact(image):
    try:
        img_tensor = preprocess(image).unsqueeze(0).to(device)

        visual_probes = {
            "shape": [
                "a mummiform or wrapped shape",
                "a beetle or oval shape",
                "a human or animal figurine shape",
                "a flat rectangular plaque shape",
                "a cylindrical or vessel shape",
                "a box or container shape"
            ],
            "material": [
                "made of blue or green faience glaze",
                "made of dark bronze or copper metal",
                "made of white or grey limestone",
                "made of gold or gilded material",
                "made of red or brown terracotta clay",
                "made of black basalt stone"
            ],
            "surface": [
                "with hieroglyphic inscriptions or text",
                "with carved relief decoration",
                "with painted decoration",
                "with smooth undecorated surface",
                "with animal or deity iconography"
            ]
        }

        observations = {}
        for feature, probes in visual_probes.items():
            tokens = clip.tokenize(probes).to(device)
            with torch.no_grad():
                img_feat  = model.encode_image(img_tensor)
                txt_feat  = model.encode_text(tokens)
                img_feat /= img_feat.norm(dim=-1, keepdim=True)
                txt_feat /= txt_feat.norm(dim=-1, keepdim=True)
                sim = (100.0 * img_feat @ txt_feat.T).softmax(dim=-1)
            top_idx = sim[0].argmax().item()
            observations[feature] = probes[top_idx]

        prompt = (
            f"Examine this Egyptian artifact and explain your reasoning.\\n\\n"
            f"[Observation]\\n"
            f"- Shape:    {observations[chr(39)+'shape'+chr(39)]}\\n"
            f"- Material: {observations[chr(39)+'material'+chr(39)]}\\n"
            f"- Surface:  {observations[chr(39)+'surface'+chr(39)]}\\n\\n"
            f"[Reasoning]\\n"
        )

        encoded = tokenizer(prompt, return_tensors="pt").to(device)
        with torch.no_grad():
            output_ids = decoder.generate(
                encoded["input_ids"],
                attention_mask=encoded["attention_mask"],
                max_new_tokens=150,
                temperature=0.7,
                do_sample=True,
                pad_token_id=tokenizer.eos_token_id
            )
        return tokenizer.decode(output_ids[0], skip_special_tokens=True)

    except Exception as e:
        return f"Error: {str(e)}"

demo = gr.Interface(
    fn=analyze_artifact,
    inputs=gr.Image(type="pil", label="Upload Egyptian Artifact Image"),
    outputs=gr.Textbox(label="Model Reasoning", lines=15),
    title="🏺 Egyptian_Artifact_VLM",
    description="""
**Vision-Language Reasoning for Ancient Egyptian Artifacts (700–330 BCE)**

Upload an image of a Late Period Egyptian artifact.
The model reasons about what it is — not just a label, but *why*,
citing visible features like shape, material, and surface decoration.

Built with CLIP + distilgpt2 | British Museum Collection | Late Period Egypt
    """,
    theme=gr.themes.Soft()
)

demo.launch()
'''

with open('/content/drive/MyDrive/Egyptian_Artifact_VLM/hf_space/app.py', 'w') as f:
    f.write(app_code)

print("✓ app.py created!")

import shutil

shutil.make_archive(
    '/content/drive/MyDrive/Egyptian_Artifact_VLM_export',
    'zip',
    '/content/drive/MyDrive/Egyptian_Artifact_VLM'
)
print("✓ Zipped!")

import subprocess
subprocess.run(['jupyter', 'nbconvert', '--ClearMetadataPreprocessor.enabled=True',
                '--to', 'notebook', '--inplace',
                '/content/drive/MyDrive/Egyptian_Artifact_VLM/Egyptian_Artifact_VLM.ipynb'])
print("✓ Metadata cleared!")